### ISSUE TITLE
gk bisa kebuka 

### ISSUE THREAD

**Issue by KindiSubarkah** [nafplann/codeigniter-alumni-app#9]
gk bisa kebuka bang. mau tak kembangin tak tambah qusionernya buat alumninya nantinya. apa harus pake xampp php 7? aku pake xampp 3.2.1

**Comment by nafplann** [comment]
@KindiSubarkah error nya apa ya bro? kalau soal xampp yang penting php nya versi 5.6 ke atas bro

**Comment by KindiSubarkah** [comment]
object not found padahal databasenya udah tak dump di phpmyadmin

**Comment by nafplann** [comment]
bisa di screenshot bro, terus kirim ke nafplann@gmail.com. nanti saya coba
bantu

**Comment by KindiSubarkah** [comment]
fixed thanks. ternyta folder di htdocsnya harus sesuai dengan yang di config.php

**Comment by nafplann** [comment]
@KindiSubarkah terima kasih sudah ngasih info bro, tiket nya saya close ya
